-- GENERATED by C->Haskell Compiler, version 0.26.1 Budburst, 4 April 2015 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "src/Codec/Compression/LZ4/Internal/LZ4HC.chs" #-}
{-# LANGUAGE CPP #-}
module Codec.Compression.LZ4.Internal.LZ4HC where



