resolver: lts-5.11
packages:
- '.'
extra-deps:
flags: {}
extra-package-dbs: []
# system-ghc: true
# arch: x86_64
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
compiler-check: newer-minor
